name: radio_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.1
  http: 0.12.0+2
  audioplayers: ^0.14.0
  sliding_up_panel: ^0.3.6
  #flutter_media_notification: ^1.2.6
  sqflite: 1.2.0
  share: 0.6.3+4
  flutter_webview_plugin: 0.3.10
  firebase_messaging: 6.0.3
  app_review: 1.0.0
  flutter_local_notifications: 0.8.4+3
  path_provider: 1.5.1
  phone_state_i: 0.0.3
  admob_flutter: ^0.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/Favorites.db